var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgs64a._.js")
R.c("server/chunks/ssr/0qwv_next_dist_esm_build_templates_app-page_0jils.~.js")
R.c("server/chunks/ssr/[root-of-the-server]__0famqc_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ts6iyv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ms8ci._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_0~pgy-o._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_forbidden_0mwn.de.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_unauthorized_0ybturi.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_global-error_0h1z.p9.js")
R.c("server/chunks/ssr/code_job-crawler_web_0dvl-k8._.js")
R.c("server/chunks/ssr/code_job-crawler_web_app_(dashboard)_profile_layout_tsx_0tm5fmf._.js")
R.c("server/chunks/ssr/0dyr_web__next-internal_server_app_(dashboard)_profile_page_actions_0z2vxit.js")
R.m(33886)
module.exports=R.m(33886).exports
