var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/jobs/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wfsn_b._.js")
R.c("server/chunks/ssr/0qwv_next_dist_0g3.s3-._.js")
R.c("server/chunks/ssr/0qwv_next_dist_esm_build_templates_app-page_0eah70x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0famqc_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ts6iyv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ms8ci._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_0~pgy-o._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_forbidden_0mwn.de.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_unauthorized_0ybturi.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_global-error_0h1z.p9.js")
R.c("server/chunks/ssr/code_job-crawler_web_0dvl-k8._.js")
R.c("server/chunks/ssr/code_job-crawler_web_app_(dashboard)_jobs_layout_tsx_04po.rk._.js")
R.c("server/chunks/ssr/0tz5_job-crawler_web__next-internal_server_app_(dashboard)_jobs_page_actions_0wp_7_r.js")
R.m(58184)
module.exports=R.m(58184).exports
