"""SOC code to pool_family seed rows from h1b_integration_guide.md."""

SOC_TO_POOL_SEED: list[dict[str, str | None]] = [
    {"soc_code": "15-1252", "soc_title": "Software Developers", "pool_family": "SWE", "domain_hint": "Software"},
    {
        "soc_code": "15-1253",
        "soc_title": "Software Quality Assurance Analysts",
        "pool_family": "SWE",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-1211",
        "soc_title": "Computer Systems Analysts",
        "pool_family": "SWE",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-1299",
        "soc_title": "Computer Occupations, All Other",
        "pool_family": "SWE",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-2051",
        "soc_title": "Data Scientists",
        "pool_family": "DATA_SCIENTIST",
        "domain_hint": "Data_Analytics",
    },
    {
        "soc_code": "15-1243",
        "soc_title": "Database Architects",
        "pool_family": "DATA_ENGINEER",
        "domain_hint": "Data_Analytics",
    },
    {
        "soc_code": "15-1245",
        "soc_title": "Database Administrators",
        "pool_family": "DATA_ENGINEER",
        "domain_hint": "Data_Analytics",
    },
    {
        "soc_code": "15-2041",
        "soc_title": "Statisticians",
        "pool_family": "DATA_ANALYST",
        "domain_hint": "Data_Analytics",
    },
    {
        "soc_code": "15-2031",
        "soc_title": "Operations Research Analysts",
        "pool_family": "DATA_ANALYST",
        "domain_hint": "Data_Analytics",
    },
    {
        "soc_code": "15-1244",
        "soc_title": "Network and Computer Systems Administrators",
        "pool_family": "DEVOPS_ENGINEER",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-1212",
        "soc_title": "Information Security Analysts",
        "pool_family": "SECURITY_ENGINEER",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-1232",
        "soc_title": "Computer User Support Specialists",
        "pool_family": "SUPPORT_ENGINEER",
        "domain_hint": "Software",
    },
    {
        "soc_code": "15-1241",
        "soc_title": "Computer Network Architects",
        "pool_family": "DEVOPS_ENGINEER",
        "domain_hint": "Software",
    },
    {
        "soc_code": "11-3021",
        "soc_title": "Computer and Information Systems Managers",
        "pool_family": "TECHNICAL_PROGRAM_MANAGER",
        "domain_hint": "Management",
    },
    {
        "soc_code": "11-9041",
        "soc_title": "Architectural and Engineering Managers",
        "pool_family": "TECHNICAL_PROGRAM_MANAGER",
        "domain_hint": "Management",
    },
    {
        "soc_code": "17-2061",
        "soc_title": "Electrical Engineers",
        "pool_family": "HARDWARE_ENGINEER",
        "domain_hint": "Hardware_Electrical",
    },
    {
        "soc_code": "17-2071",
        "soc_title": "Electrical and Electronics Engineers",
        "pool_family": "HARDWARE_ENGINEER",
        "domain_hint": "Hardware_Electrical",
    },
    {
        "soc_code": "17-2141",
        "soc_title": "Mechanical Engineers",
        "pool_family": "SYSTEMS_ENGINEER",
        "domain_hint": "Mechanical",
    },
    {
        "soc_code": "17-2051",
        "soc_title": "Civil Engineers",
        "pool_family": "SYSTEMS_ENGINEER",
        "domain_hint": "Mechanical",
    },
    {
        "soc_code": "17-2112",
        "soc_title": "Industrial Engineers",
        "pool_family": "SYSTEMS_ENGINEER",
        "domain_hint": "Industrial_Automation",
    },
    {
        "soc_code": "17-2011",
        "soc_title": "Aerospace Engineers",
        "pool_family": "AEROSPACE_ENGINEER",
        "domain_hint": "Aerospace_Defense",
    },
    {
        "soc_code": "17-2199",
        "soc_title": "Engineers, All Other",
        "pool_family": "SYSTEMS_ENGINEER",
        "domain_hint": None,
    },
    {
        "soc_code": "19-1042",
        "soc_title": "Medical Scientists",
        "pool_family": "RESEARCH_SCIENTIST",
        "domain_hint": "Research_Science",
    },
    {
        "soc_code": "19-2041",
        "soc_title": "Environmental Scientists",
        "pool_family": "RESEARCH_SCIENTIST",
        "domain_hint": "Research_Science",
    },
    {
        "soc_code": "19-2099",
        "soc_title": "Physical Scientists, All Other",
        "pool_family": "RESEARCH_SCIENTIST",
        "domain_hint": "Research_Science",
    },
    {
        "soc_code": "15-2099",
        "soc_title": "Mathematical Science Occupations, All Other",
        "pool_family": "DATA_SCIENTIST",
        "domain_hint": "Data_Analytics",
    },
]
