var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(profile-flow)/profile/review/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l023zq._.js")
R.c("server/chunks/ssr/0qwv_next_dist_esm_build_templates_app-page_0a9-kn0.js")
R.c("server/chunks/ssr/[root-of-the-server]__0famqc_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ts6iyv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ms8ci._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_0~pgy-o._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_forbidden_0mwn.de.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_unauthorized_0ybturi.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_global-error_0h1z.p9.js")
R.c("server/chunks/ssr/code_job-crawler_web_0f8hp4p._.js")
R.c("server/chunks/ssr/0_lc__next-internal_server_app_(profile-flow)_profile_review_page_actions_02vqm2-.js")
R.m(77368)
module.exports=R.m(77368).exports
