// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/applied" | "/dashboard" | "/emails" | "/filters" | "/jobs" | "/jobs/all" | "/jobs/applied" | "/jobs/liked" | "/jobs/recommended" | "/login" | "/onboarding" | "/preferences" | "/profile" | "/profile/confirm" | "/profile/job-intent" | "/profile/processing" | "/profile/review" | "/profile/upload" | "/recommended" | "/resume" | "/saved" | "/settings" | "/signup" | "/unsubscribe"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/profile/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/emails" | "/jobs" | "/profile" | "/resume"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/profile/[...path]": { "path": string[]; }
  "/app": {}
  "/applied": {}
  "/dashboard": {}
  "/emails": {}
  "/filters": {}
  "/jobs": {}
  "/jobs/all": {}
  "/jobs/applied": {}
  "/jobs/liked": {}
  "/jobs/recommended": {}
  "/login": {}
  "/onboarding": {}
  "/preferences": {}
  "/profile": {}
  "/profile/confirm": {}
  "/profile/job-intent": {}
  "/profile/processing": {}
  "/profile/review": {}
  "/profile/upload": {}
  "/recommended": {}
  "/resume": {}
  "/saved": {}
  "/settings": {}
  "/signup": {}
  "/unsubscribe": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/emails": never
  "/jobs": never
  "/profile": never
  "/resume": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
