var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(marketing)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00shnrp._.js")
R.c("server/chunks/ssr/0qwv_next_dist_esm_build_templates_app-page_0_x42lf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0famqc_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ts6iyv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ms8ci._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_0~pgy-o._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_forbidden_0mwn.de.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_unauthorized_0ybturi.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_global-error_0h1z.p9.js")
R.c("server/chunks/ssr/code_job-crawler_web_app_(marketing)_layout_tsx_0s1jnay._.js")
R.c("server/chunks/ssr/code_job-crawler_web__next-internal_server_app_(marketing)_page_actions_0q._~tl.js")
R.m(86039)
module.exports=R.m(86039).exports
