var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/resume/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x64~sm._.js")
R.c("server/chunks/ssr/0qwv_next_dist_esm_build_templates_app-page_0wbris6.js")
R.c("server/chunks/ssr/[root-of-the-server]__0famqc_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ts6iyv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ms8ci._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_0~pgy-o._.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_forbidden_0mwn.de.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_unauthorized_0ybturi.js")
R.c("server/chunks/ssr/0qwv_next_dist_client_components_builtin_global-error_0h1z.p9.js")
R.c("server/chunks/ssr/code_job-crawler_web_0dvl-k8._.js")
R.c("server/chunks/ssr/code_job-crawler_web_app_(dashboard)_resume_layout_tsx_09nkz8a._.js")
R.c("server/chunks/ssr/0dyr_web__next-internal_server_app_(dashboard)_resume_page_actions_0r1y--d.js")
R.m(33388)
module.exports=R.m(33388).exports
